
### get users
GET http://localhost:8000/siteUser/get_users
Accept: application/json

### login 
POST http://localhost:8000/siteUser/login_user/
Content-Type: application/json

{
  "email":"newuser1@example.com",
  "password":"ohm123ohm"
}


### Get simulations
GET http://localhost:8000/sim/get_sim/

Content-Type: application/json

### Get comments
GET http://localhost:8000/comment/get_comments/
Content-Type: application/json

### Get comments by id
GET http://localhost:8000/comment/get_comments_by_sim/52/
Content-Type: application/json

### Get comments by sim
POST http://localhost:8000/comment/add_comment/52/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0MzQzNDYyLCJpYXQiOjE3MjQzNDA0NjIsImp0aSI6ImI3NjEyZDdlZjg3ZjRmNTJhZmZjMTdkODZiYjg1YTY0IiwidXNlcl9pZCI6Mn0.05IJpLWS10cHTsHG3GDgkxaMG35pgyuu5GT7aIR5_34
Content-Type: application/json

{
  "message":"comment by newuser1@gmail.com"
}

### delete comments by sim
DELETE http://localhost:8000/comment/delete_comment/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0MzQ4MTk0LCJpYXQiOjE3MjQzNDUxOTQsImp0aSI6ImNiNDVjYjc1ZjNjODQ5NWFhYWZkNjI2ODFlNTliNThhIiwidXNlcl9pZCI6Mn0.g1PSJItLMSCacShgkTTQHX6BjAxV4N_Y08xs4Q-crbo
Content-Type: application/json

### Get subcomments 
GET http://localhost:8000/subComment/get_subcomments/
Content-Type: application/json

### Get subcomments by comment 
GET http://localhost:8000/subComment/get_subcomments_by_id/7/
Content-Type: application/json

### create sub comment
POST http://localhost:8000/subComment/create_subComment/7/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0MzQ2Mjg5LCJpYXQiOjE3MjQzNDMyODksImp0aSI6IjVjZDE5ZjcwNmJkZDRmYjc4YjYxZGIyYzQwODcyZWRiIiwidXNlcl9pZCI6MX0.JybGJVTlgub_6Mtmi-iF0_Xdo5KAqAFloCdddlCLeyU
Content-Type: application/json

{
  "message":"subcomment by newuser12@gmail.com"
}

### create sub comment
DELETE http://localhost:8000/subComment/delete_subcomment/6/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0MzQ4MDk4LCJpYXQiOjE3MjQzNDUwOTgsImp0aSI6IjQzMjAzOGJiZDY1MDRlMDJiNzUzYzgwNTU1MWIzY2MwIiwidXNlcl9pZCI6MX0.mzH-4IQggR-_PkMiKD1Am5SzjHStju4DNU32gn9e0N8
Content-Type: application/json
