version: '3.8'

services:
  mech-server:
    image: ohmv10/mech-server:v1.2
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-!7&aq!#k$7+6vg^g)r(5#5_-@sm5&0be1anjiz7(sib@mt+0+@
      DEBUG: 'False'
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgresql://mech_sim_vault_user:b2s3wK1puEcY2Kvx7UCdjyA2js9saR6a@dpg-cr8svpt6l47c73bocem0-a.singapore-postgres.render.com/mech_sim_vault
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      MYSQL_DATABASE: mech_sim_db
      MYSQL_USER: mechsimvault-server
      MYSQL_PASSWORD: Ohm@42@42@42@
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    networks:
      - mech-net

  mech-client:
    image: ohmv10/mech-client:v1.0
    ports:
      - "3000:3000"
    networks:
      - mech-net

  mysql-test:
    image: mysql:9.0.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mech_sim_db
      MYSQL_USER: mechsimvault-server
      MYSQL_PASSWORD: Ohm@42@42@42@
    ports:
      - "3306:3306"
    volumes:
      - /home/ohm/docker-volume:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mech-net

volumes:
  mysql-data:
    driver: local

networks:
  mech-net:
    driver: bridge
