version: '3.8'

services:
  mech-server:
    image: ohmv10/mech-server:v1.2
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-!7&aq!#k$7+6vg^g)r(5#5_-@sm5&0be1anjiz7(sib@mt+0+@
      DEBUG: 'False'
      ALLOWED_HOSTS: localhost,127.0.0.1,your-vercel-domain.vercel.app
      DATABASE_URL: postgresql://mech_sim_vault_user:b2s3wK1puEcY2Kvx7UCdjyA2js9saR6a@dpg-cr8svpt6l47c73bocem0-a.singapore-postgres.render.com/mech_sim_vault
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      MYSQL_DATABASE: mech_sim_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p password", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
    networks:
      - mech-net

  mech-client:
    image: ohmv10/mech-client:v1.0
    ports:
      - "3000:3000"
    networks:
      - mech-net

  mysql:
    image: mysql:9.0.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mech_sim_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /home/docker-volume:/var/lib/mysql
    networks:
      - mech-net

volumes:
  mysql-data:
    driver: local

networks:
  mech-net:
    driver: bridge
