apiVersion: v1
kind: ConfigMap
metadata:
  name: mech-server-config
  namespace: mech-server
data:
  DEBUG: 'False'
  ALLOWED_HOSTS: '*'
  DATABASE_URL: postgresql://mech_sim_vault_user:b2s3wK1puEcY2Kvx7UCdjyA2js9saR6a@dpg-cr8svpt6l47c73bocem0-a.singapore-postgres.render.com/mech_sim_vault
  CORS_ALLOWED_ORIGINS: 'https://abc.mechsimvault'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mech-server
data:
  MYSQL_DATABASE: mech_sim_db
  MYSQL_USER: mechsimvault-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
  namespace: mech-server
data:
  init.sql: |
    DROP USER IF EXISTS 'mechsimvault-server'@'%';
    CREATE USER 'mechsimvault-server'@'%' IDENTIFIED BY 'Ohm@42@42@42@';
    GRANT ALL PRIVILEGES ON mech_sim_db.* TO 'mechsimvault-server'@'%';
    FLUSH PRIVILEGES;

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-cm
  namespace: mech-server
data:
 default.conf: |
    server {
        listen 80;
        server_name localhost;
        location /media {
          root  /usr/share/nginx/html;
        }
        location / {
          proxy_pass http://mech-server-service:8000;
        }
    }