apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mech-server  
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: mysql-storageclass

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  namespace: mech-server
  labels:
    app: django-media-pvc
spec:
  storageClassName: media-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi