apiVersion: v1
kind: Secret
metadata:
  name: mech-server-secret
  namespace: mech-server
type: Opaque
data:
  SECRET_KEY: ZGFuZ2pvLWluc2VjdXJlLSE3JmFxISNrJDcrNnZnXmcpcig1IzUtLUBzbTUmbkJlMWFuanJpZjdmc2liQG10KzArQA==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mech-server
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # 'password' encoded in base64
  mysql-password: T2htQDQyQDQyQDQyQAo=  # 'Ohm@42@42@42@' encoded in base64
  