version: '3.8'

services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mech_sim_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /home/docker-volume:/var/lib/mysql
    networks:
      - mech-net

volumes:
  mysql-data:
    driver: local


networks:
  mech-net:
    driver: bridge