# Generated by Django 5.1 on 2024-10-06 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(default=datetime.date(2024, 10, 6), verbose_name='upload data')),
                ('dislikes', models.IntegerField(default=0, verbose_name='dislikes')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Simulation title')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Simulation title')),
                ('Softwares', models.CharField(default='', max_length=50, verbose_name='Simulation title')),
                ('simulation_image', models.ImageField(default='simulations/default_photo.png', upload_to='simulations/', verbose_name='Simulation disp image')),
                ('zip_file', models.FileField(blank=True, upload_to='simulations/', verbose_name='Simulation Zip File')),
                ('zip_photos', models.FileField(blank=True, upload_to='simulations/', verbose_name='Simulation Images')),
            ],
        ),
    ]
