# Generated by Django 5.1 on 2024-10-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='site user'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Site User'),
        ),
        migrations.AddField(
            model_name='likes',
            name='sim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.simulation', verbose_name='simuation id'),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user_id', 'sim_id')},
        ),
    ]
