# Generated by Django 5.1 on 2024-10-08 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateField(default=datetime.date(2024, 10, 8), verbose_name='upload data'),
        ),
    ]
