# Generated by Django 5.1 on 2024-10-26 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_alter_simulation_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateField(default=datetime.date(2024, 10, 26), verbose_name='upload data'),
        ),
    ]
