# Generated by Django 5.1 on 2024-11-08 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_alter_simulation_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateField(default=datetime.date(2024, 11, 8), verbose_name='upload data'),
        ),
    ]
