apiVersion: v1
kind: ConfigMap
metadata:
  name: mech-server-config
data:
  DEBUG: 'False'
  ALLOWED_HOSTS: localhost,127.0.0.1,your-vercel-domain.vercel.app
  DATABASE_URL: postgresql://mech_sim_vault_user:b2s3wK1puEcY2Kvx7UCdjyA2js9saR6a@dpg-cr8svpt6l47c73bocem0-a.singapore-postgres.render.com/mech_sim_vault
  CORS_ALLOWED_ORIGINS: http://localhost:3001

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: mech_sim_db
  MYSQL_USER: mechsimvault-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
data:
  init.sql: |
    DROP USER IF EXISTS 'mechsimvault-server'@'%';
    CREATE USER 'mechsimvault-server'@'%' IDENTIFIED BY 'Ohm@42@42@42@';
    GRANT ALL PRIVILEGES ON mech_sim_db.* TO 'mechsimvault-server'@'%';
    FLUSH PRIVILEGES;
