apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  storageClassName: "mysql-storageclass"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
