apiVersion: v1
kind: Secret
metadata:
  name: mech-server-secret
type: Opaque
data:
  SECRET_KEY: ZGFuZ2pvLWluc2VjdXJlLSE3JmFxISNrJDcrNnZnXmcpcig1IzUtLUBzbTUmbkJlMWFuanJpZjdmc2liQG10KzArQA==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=
  mysql-database: bWVjaC1zaW0tZGI=
  mysql-user: YWRtaW4=
  mysql-password: cGFzc3dvcmQ=
