# Generated by Django 5.1 on 2024-08-21 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(default=django.utils.timezone.now, verbose_name='upload data')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('dislikes', models.IntegerField(default=0, verbose_name='dislikes')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Simulation title')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Simulation title')),
                ('Softwares', models.CharField(default='', max_length=50, verbose_name='Simulation title')),
                ('zip_file', models.FileField(upload_to='simulations/zips/', verbose_name='Simulation Zip File')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Site User')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='simulations/photos/', verbose_name='Simulation Photo')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='simulations.simulation')),
            ],
        ),
    ]
