# Generated by Django 5.1 on 2024-08-22 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='simulation_image',
            field=models.ImageField(default='simulations/default_photo.png', upload_to='simulations/', verbose_name='Simulation disp image'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='zip_photos',
            field=models.FileField(blank=True, upload_to='simulations/', verbose_name='Simulation Images'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateField(default=datetime.date(2024, 8, 22), verbose_name='upload data'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='simulations/', verbose_name='Simulation Zip File'),
        ),
        migrations.DeleteModel(
            name='SimulationPhoto',
        ),
    ]
