# Generated by Django 5.1 on 2024-08-23 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_simulation_simulation_image_simulation_zip_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='upload_date',
            field=models.DateField(default=datetime.date(2024, 8, 23), verbose_name='upload data'),
        ),
    ]
