# Generated by Django 5.1 on 2024-08-25 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_remove_simulation_likes_alter_simulation_upload_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user_id', 'sim_id')},
        ),
    ]
