# Generated by Django 5.1 on 2024-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteUser', '0002_siteuser_bio_siteuser_contact_info_siteuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/base.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
