# Generated by Django 5.1 on 2024-10-06 20:29

import apps.siteUser.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_picture', models.ImageField(blank=True, default='profile_picture/base.jpg', null=True, upload_to=apps.siteUser.models.PathAndRename())),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email id')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('full_name', models.CharField(default='Default name', max_length=50, verbose_name='full name')),
                ('bio', models.CharField(blank=True, default='', max_length=500, verbose_name='bio')),
                ('institution', models.CharField(blank=True, default='', max_length=250, verbose_name='institution')),
                ('role', models.CharField(blank=True, default='', max_length=250, verbose_name='role')),
                ('country', models.CharField(blank=True, default='INDIA', max_length=250, verbose_name='country')),
                ('contact_info', models.CharField(blank=True, default='', max_length=250, verbose_name='contact info')),
                ('skills', models.CharField(blank=True, default='', max_length=250, verbose_name='skills')),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='user creation date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
