# Generated by Django 5.1 on 2024-11-08 05:35

import apps.siteUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/image.png', null=True, upload_to=apps.siteUser.models.PathAndRename()),
        ),
    ]
