# Generated by Django 5.1 on 2024-08-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userComments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='simulation_id',
            new_name='simulation',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
